### PR TITLE
UI Fix for small and medium devices

### PR DESCRIPTION
**Pull request by Mrayyan**
Fixed control layout for small and medium screen devices
Fixed uneven icon sizes
Fixed setup screen for small screen devices

## Purpose
Fixed control layout for small and medium screen devices
Fixed uneven icon sizes
Fixed setup screen for small screen devices

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
> Icon sizes
> Setup screen on small and medium size devices
> Control layout on small and medium size devices

### CODE REVIEW

**Comment by pavelprystinka** [comment]
How does it look on the large size device?
Should we consider to have different icons/layouts for large/small screens?

**Comment by Mrayyan** [comment]
> How does it look on the large size device?
> Should we consider to have different icons/layouts for large/small screens?



Haven't tested on large size devices yet. We will definitely need separate layouts/font sizes/icons for large ( > sw600dp) and small screen sizes. Should I work on having different layouts and font sizes for different screens?

**Comment by Mrayyan** [comment]
> How does it look on the large size device?
> Should we consider to have different icons/layouts for large/small screens?

Tested on a 10.1inch tablet. UI needs some improvements for larger screens. I have created a bug ticket and will be working on it soon.

**Review by jamchengms — DISMISSED** [review]

**Review by iaulakh — COMMENTED** [review]
Hi @Mrayyan, what is the minimum screen size that PR addresses?
I noticed on 4" screen:
Screen Shot 2021-11-15 at 7 33 52 PM

**Comment by Mrayyan** [comment]
> Hi @Mrayyan, what is the minimum screen size that PR addresses?
> I noticed on 4" screen:
> Screen Shot 2021-11-15 at 7 33 52 PM

It supports until 5inch.

**Review by ShaunaSong — DISMISSED** [review]

**Comment by lpx1989** [comment]
How about this changes works on pad screen?

**Comment by Mrayyan** [comment]
> How about this change works on pad screen?

No, this change does not work on pad screen. I did talk with Alex and he said that there is no official design guideline for the sample app on large screens. He said to file bugs for any issues I see. At the moment, the app is usable on larger screens but just some text and button sizes can increases. I have already created a bug ticket for that: https://skype.visualstudio.com/SPOOL/_workitems/edit/2632207

**Comment by Mrayyan** [comment]
> Hi @Mrayyan, what is the minimum screen size that PR addresses?
> I noticed on 4" screen:
> Screen Shot 2021-11-15 at 7 33 52 PM

Fixed now until 5inch phones.

**Comment by ShaunaSong** [comment]
Instead of changing the main layout with a smaller margin, we could build the other new XML for the small screen, same as we did for the larger screen.
image

**Comment by Mrayyan** [comment]
> Instead of changing the main layout with a smaller margin, we could build the other new XML for the small screen, same as we did for the larger screen.
> image

There isn't that much of the change that was needed for small screen devices. So I thought just to change the margin to make it usable on small screens. I don't think we need to create another layout file since the current app is usable on small screen devices with just a few minor changes in the current file.

**Review by gynono — DISMISSED** [review]

**Review by jamchengms — APPROVED** [review]

**Review by jamchengms — DISMISSED** [review]

**Review by lpeixin — DISMISSED** [review]

**Review by iaulakh — COMMENTED** [review]
@Mrayyan I noticed few things that we can fix:
1) In call screen audio icon is black (not matching to others)
2) The name banner text is very long


Screen Shot 2022-01-15 at 5 30 47 PM
Screen Shot 2022-01-15 at 5 13 54 PM

**Review by iaulakh — COMMENTED** [review]
@Mrayyan I noticed that on switching theme I can see different icon color for devices. 
Screen Shot 2022-02-01 at 1 51 56 PM

**Review by iaulakh — APPROVED** [review]

**Pull request closed without merging**
