### PR TITLE
User can see who is the active speaker

### PR DESCRIPTION
**Pull request by pavelprystinka**
## Purpose

* User can see who is the active speaker

## Does this introduce a breaking change?

```
[ ] Yes
[X] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[X] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get in a call with remote participant
* When remote participant is speaking observe highlighted border around

### CODE REVIEW

**Comment by iaulakh** [comment]
Screen Shot 2021-04-26 at 9 52 19 AM

looks good Pavel. when I speak, I was not able to see blue circle around me. so we are going to show highlight only for remote participants?

**Comment by cheukchuen** [comment]
> looks good Pavel. when I speak, I was not able to see blue circle around me. so we are going to show highlight only for remote participants?

That's probably by design provided by the Calling SDK. Same with iOS and Teams itself

**Comment by pavelprystinka** [comment]
> Screen Shot 2021-04-26 at 9 52 19 AM
> 
> looks good Pavel. when I speak, I was not able to see blue circle around me. so we are going to show highlight only for remote participants?

I do not think it is necessary - user knows when he/she is speaking. Plus there is no such info from calling SDK

**Review by iaulakh — DISMISSED** [review]

**Comment by iaulakh** [comment]
tested

**Review by palatter — DISMISSED** [review]

**Review by iaulakh — APPROVED** [review]

**Review by palatter — APPROVED** [review]

**Pull request merged**
