### PR TITLE
Remove observers to CallState when leaving a call

### PR DESCRIPTION
**Pull request by Gemakk**
## Purpose

* Prevent a race condition, which is triggered when you leave a Teams Interop call
* You may see the "You've been removed from this meeting", or see a stacktrace which indicates that it was unable to create a dialogue for an activity which was already destroyed.

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code
* Test the code

```
- Ensure that when you leave a Teams Interop meeting that you do not see a dialogue popup showing "You've been removed from this meeting", nor a logging stacktrace which indicates that an Activity was prematurely destroyed.
- Ensure all other CallState events behave as expected(e.g. Be denied joining a meeting, be kicked from the meeting)
```

### CODE REVIEW

**Review by waynemo — CHANGES_REQUESTED** [review]
We should apply these changes to main first, then it can be includes as part of the merges to feature/teams_interop.

**Review by lpeixin — COMMENTED** [review]
Tested

**Comment by Gemakk** [comment]
> We should apply these changes to main first, then it can be includes as part of the merges to feature/teams_interop.

The main branch doesn't have `callingContext.getCallStateLiveData()`.  One solution would be to implement this method in main first?

**Comment by waynemo** [comment]
> > We should apply these changes to main first, then it can be includes as part of the merges to feature/teams_interop.
> 
> The main branch doesn't have `callingContext.getCallStateLiveData()`. One solution would be to implement this method in main first?

If it's not used in main yet, we can keep it in the feature branch. But this change could be applied to main first, correct?
`callingContext.getDisplayedParticipantsLiveData().removeObservers(this);`

**Comment by Gemakk** [comment]
> If it's not used in main yet, we can keep it in the feature branch. But this change could be applied to main first, correct?
> `callingContext.getDisplayedParticipantsLiveData().removeObservers(this);`

That change happens in CallActivity.endCall(), which doesn't exist in main either.  Given that, my suggestion is to keep this change to the feature branch.

**Comment by waynemo** [comment]
> > If it's not used in main yet, we can keep it in the feature branch. But this change could be applied to main first, correct?
> > `callingContext.getDisplayedParticipantsLiveData().removeObservers(this);`
> 
> That change happens in CallActivity.endCall(), which doesn't exist in main either. Given that, my suggestion is to keep this change to the feature branch.

I suggest we do the refactoring up-front in main branch to have the `endCall()` method so that where will be less conflicts when merging the feature branch.

**Comment by iaulakh** [comment]
@Gemakk can we merge this to main and then main to teams_merge_copy? We will merge teams_merge_copy to main.

**Comment by Gemakk** [comment]
> @Gemakk can we merge this to main and then main to teams_merge_copy? We will merge teams_merge_copy to main.

We cannot, since there's code that only pertains to the interop branch.  This PR will minimize that code to a single line, however:
https://github.com/Azure-Samples/communication-services-android-calling-hero/pull/70

**Review by iaulakh — APPROVED** [review]

**Review by iaulakh — APPROVED** [review]

**Comment by Gemakk** [comment]
@waynemo @lpx1989  - This is now a single-line change

**Review by waynemo — APPROVED** [review]

**Pull request merged**
