### PR TITLE
Resume video on setup screen wakeup

### PR DESCRIPTION
**Pull request by iaulakh**
## Purpose

* Resume video on setup screen wakeup

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

### CODE REVIEW

**Review by pavelprystinka — APPROVED** [review]

**Comment by iaulakh** [comment]
Steps to test:
1) Click "Start new call"
2) Turn on Video by clicking video toggle button
3) Go to Mobile home screen "let application to go in background mode"
4) Reopen application
Expected behaviour: Video should be displayed on Setup screen

**Comment by pavelprystinka** [comment]
Code tested

**Comment by pavelprystinka** [comment]
Code tested

**Review by Gemakk — APPROVED** [review]
Tested

**Pull request merged**
