### PR TITLE
Remove default avatar when camera permissions are denied

### PR DESCRIPTION
**Pull request by Gemakk**
## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
* Open app to Setup Activity
* Open Edit Text to enter your name
* Deny camera permissions by selecting video then saying Deny, or deny it via app settings

## What to Check
Verify that the following are valid
* Ensure the Default avatar is gone

### CODE REVIEW

**Review by iaulakh — COMMENTED** [review]
Screen Shot 2021-04-26 at 9 35 02 AM

with this change permissions text is hidden when keyboard opens. looks like we need to compromise one, either hiding join button or hiding text. May be we can discuss with Leah the less impacted change?

**Comment by Gemakk** [comment]
How much of the text it obscures depends on the size of the screen.  Here's what it looks like for a Pixel 2:
image

**Comment by iaulakh** [comment]
think it is ok. The keyboard can be closed to see back text.

**Review by iaulakh — DISMISSED** [review]

**Comment by iaulakh** [comment]
tested

**Review by palatter — DISMISSED** [review]

**Review by palatter — APPROVED** [review]

**Review by iaulakh — APPROVED** [review]

**Pull request merged**
